name: Audit Dependencies

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # or the version you're using

      - name: Install dependencies
        run: npm install

      - name: Run npm audit
        run: npm audit --production

      - name: Audit with snyk
        run: npm install -g snyk && snyk test
